"""empty message

Revision ID: 5278bb3f0ee4
Revises: 27c736095c20
Create Date: 2021-11-24 17:54:14.207754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5278bb3f0ee4'
down_revision = '27c736095c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_name_key', 'venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_name_key', 'venue', ['name'])
    # ### end Alembic commands ###
